#!/bin/bash

set -eu
cmd=${1?Command expected.}
shift

getid() {
    id=$(basename "$1" | grep -Po '^\d+')
    if [ "${2-}" = "-r" ]; then
        echo $id
    else
        echo $id | sed 's/^0*//' # Remove leading zeroes
    fi
}

populate() {
    while read id fname; do
        ln -s "$(tagmage path $id)" "$(printf %05d $id)-${fname}"
    done
}

populate-tag() {
    mkdir "$1"
    cd "$1"
    tagmage list "$@" | populate
    cd ..

    # Remove tag if no files exist.
    if [ "$(ls "$1" | wc -l)" -eq 0 ]; then
        rmdir "$1"
    fi
}

setupdir() {
    filedir=${TAD_HOME-/tmp/tad-$USER}
    mkdir -p $filedir
    rm -rf $filedir/*
    cd $filedir
}


case $cmd in
    edit)
        file_id=$(getid "$1")
        tagmage edit $file_id "$2"
        mv "$1" "$(getid "$1" -r)-${2}"
        ;;
    list)
        setupdir
        tagmage list "$@" | populate &
        ;;
    tags)
        setupdir

        tagmage tags | while read tag; do
            populate-tag "$tag" "$@" &
        done

        # List untagged files if displaying all files.
        if [ "$#" -eq 0 ]; then
            populate-tag ":untagged" &
        fi
        ;;
    tag)
        file_id=$(getid "$1")
        shift
        tagmage tag $file_id "$@"
        ;;
    untag)
        file_id=$(getid "$1")
        shift
        tagmage untag $file_id "$@"
        ;;
    rm)
        while [ "$#" -gt 0 ]; do
            tagmage rm $(getid "$1")
            rm "$1"
            shift
        done
        ;;
esac
