#!/bin/bash

set -eu
cmd=${1?Command expected.}
shift

getid() {
    id=$(basename "$1" | grep -Po '^\d+')
    if [ "${2-}" = "-r" ]; then
        echo $id
    else
        echo $id | sed 's/^0*//' # Remove leading zeroes
    fi
}

getext() {
    echo "$1" | grep -Po '\..+' || true
}

populate() {
    while read id ext fname; do
        ln -s "$(tagmage path $id)" "$(printf %05d $id)-${fname}${ext}"
    done
}

populate-tag() {
    mkdir "$1"
    cd "$1"
    tagmage list "$@" | populate
    cd ..

    # Remove tag if no images exist.
    if [ "$(ls "$1" | wc -l)" -eq 0 ]; then
        rmdir "$1"
    fi
}

setupdir() {
    imgdir=${TAD_HOME-/tmp/tad-$USER}
    rm -rf $imgdir
    mkdir -p $imgdir
    cd $imgdir
}


case $cmd in
    add)
        # This has no behavior difference to the backend.
        tagmage add "$@"
        ;;
    edit)
        image_id=$(getid "$1")
        ext=$(getext "$1")
        tagmage edit $image_id "$2"
        mv "$1" "$(getid "$1" -r)-${2}${ext}"
        ;;
    list)
        setupdir
        tagmage list "$@" | populate &
        ;;
    tags)
        setupdir

        tagmage tags | while read tag; do
            populate-tag "$tag" "$@" &
        done

        # List untagged images if displaying all images.
        if [ "$#" -eq 0 ]; then
            mkdir ':untagged'
            cd ':untagged'
            tagmage untagged | populate &
        fi
        ;;
    tag)
        image_id=$(getid "$1")
        shift
        tagmage tag $image_id "$@"
        ;;
    untag)
        image_id=$(getid "$1")
        shift
        tagmage untag $image_id "$@"
        ;;
    rm)
        while [ "$#" -gt 0 ]; do
            tagmage rm $(getid "$1")
            rm "$1"
            shift
        done
        ;;
esac
