.TH "TAGMAGE" "1" "16 Aug 2018" "v@@VERSION@@" "tagmage"

.SH "NAME"
tagmage - save, organize and list files via tags.

.SH "SYNOPSIS"
.B tagmage
.RI [ OPTION ]...
.RI [ COMMAND ]
...

.SH "DESCRIPTION"


.PP
.B -f
.I SAVE
.RS 4
Sets the save directory to
.IR SAVE .
If this option is not present, the save directory will be set to
.I $TAGMAGE_HOME
if the variable is set. Else, it will be set to
.IR $XDG_HOME /tagmage
if
.I $XDG_HOME
is set. Else, it will be set to
.IR $HOME /.local/share/tagmage "" .
.RE

.SH "COMMANDS"

.PP
.B add
.RI [ "" "-t " TAG1 " " TAG2 " " ... " +" "" ]
.I FILES..
.RS 4
Copies
.I FILES
to the save file and outputs the IDs of each file to standard output,
delimited by a newline. If the
.I -t
flag is provided, it accepts a series of tag names followed by a
.IR + . All tags will be added to the file.

.RE

.PP
.B edit
.I FILE TITLE
.RS 4
Changes
.IR FILE 's
title to
.IR TITLE .
.RE

.PP
.B list
.RI [ TAGS.. ]
.RS 4
Lists every file in the database. If tags are provided, it will only
list files that has every provided tag.
.RE

.PP
.B untagged
.RS
Lists all files without tags.
.RE

.PP
.B path
.RI [ FILES.. ]
.RS 4
Echoes the path of the save directory to standard output. If
.I FILES
is provided, it lists the path of the file id.
.RE

.PP
.B tag
.I FILE
.RI [ TAGS.. ]
.RS 4
Add
.I TAGS
to
.IR FILE .
If a tag is already assigned to
.IR FILE ,
the program silently succeeds.
.RE

.PP
.B untag
.I FILE
.RI [ TAGS.. ]
.RS 4
Removes
.I TAGS
from
.IR FILE .
If a tag was not yet assigned to
.IR FILE ,
the program silently succeeds.
.RE

.PP
.B tags
.RI [ FILE ]
.RS
Prints a list of newline-delimited tags the file has to standard
output. If
.I FILE
is provided, it prints a list of tags that the file has.

.PP
.B rm
.I FILES..
.RS 4
Removes every file listed from the database.

.SH "SEE ALSO"

.BR tad (1)
